import mongoose, { Schema, Document, Types } from 'mongoose';

export interface ICartItem {
  _id?: Types.ObjectId; // Automatically generated by Mongoose for subdocuments
  menuItem: Types.ObjectId;
  quantity: number;
  unitPrice: number;
  subtotal: number;
  notes?: string;
}

export interface ICart extends Document {
  restaurantId: Types.ObjectId;
  sessionId: Types.ObjectId;
  items: Types.DocumentArray<ICartItem & Document>;
  subtotal: number;
  tax: number;
  discount: number;
  grandTotal: number;
  createdAt: Date;
  updatedAt: Date;
}

const cartItemSchema = new Schema<ICartItem>(
  {
    menuItem: {
      type: Schema.Types.ObjectId,
      ref: 'MenuItem',
      required: true,
    },
    quantity: {
      type: Number,
      required: true,
      min: [1, 'Quantity must be at least 1'],
    },
    unitPrice: {
      type: Number,
      required: true,
      min: 0,
    },
    subtotal: {
      type: Number,
      required: true,
      min: 0,
    },
    notes: {
      type: String,
      trim: true,
      maxlength: [200, 'Notes cannot exceed 200 characters'],
    },
  },
  { _id: true }
);

const cartSchema = new Schema<ICart>(
  {
    restaurantId: {
      type: Schema.Types.ObjectId,
      ref: 'Restaurant',
      required: true,
      index: true,
    },
    sessionId: {
      type: Schema.Types.ObjectId,
      ref: 'TableSession',
      required: true,
      unique: true, // One cart per session
    },
    items: [cartItemSchema],
    subtotal: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    tax: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    discount: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    grandTotal: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
    collection: 'carts',
  }
);

export const Cart = mongoose.model<ICart>('Cart', cartSchema);
