// data/alerts.ts
import { Alert } from '../components/Alerts/index';

export const INITIAL_ALERTS: Alert[] = [
  {
    id: '1',
    title: 'Plan Limit Exceeded',
    description: 'Urban Bites has exceeded 100% of their monthly order limit (1500/1500). Orders are now being rejected. Immediate action required.',
    type: 'critical',
    status: 'new',
    entity: 'Urban Bites',
    entityType: 'restaurant',
    timestamp: '2026-05-16T14:30:00Z',
    actionLabel: 'Upgrade Plan',
    tags: ['billing', 'limits'],
  },
  {
    id: '2',
    title: 'High Usage Alert',
    description: 'Spice Paradise has reached 92% of their plan usage. An upgrade recommendation email has been sent automatically.',
    type: 'warning',
    status: 'new',
    entity: 'Spice Paradise',
    entityType: 'restaurant',
    timestamp: '2026-05-16T13:45:00Z',
    actionLabel: 'View Details',
    tags: ['usage'],
  },
  {
    id: '3',
    title: 'Failed Transaction',
    description: 'Payment failed for order ORD-2026-001238. Amount: ₹670. Reason: Insufficient funds. Retry attempted 3/3 times.',
    type: 'critical',
    status: 'read',
    entityType: 'payment',
    timestamp: '2026-05-16T12:10:00Z',
    actionLabel: 'Retry Payment',
    tags: ['payment'],
  },
  {
    id: '4',
    title: 'New Restaurant Signup',
    description: 'Bombay Street Kitchen has completed registration and is pending approval. Documents submitted for KYC verification.',
    type: 'info',
    status: 'new',
    entity: 'Bombay Street Kitchen',
    entityType: 'restaurant',
    timestamp: '2026-05-16T11:00:00Z',
    actionLabel: 'Review Application',
    tags: ['onboarding'],
  },
  {
    id: '5',
    title: 'System Latency Spike',
    description: 'API response time exceeded 2000ms threshold for 12 consecutive minutes. Affected endpoints: /orders, /menu. Auto-scaled at 11:52 AM.',
    type: 'warning',
    status: 'acknowledged',
    entityType: 'system',
    timestamp: '2026-05-16T11:40:00Z',
    tags: ['performance', 'system'],
  },
  {
    id: '6',
    title: 'Unusual Login Activity',
    description: 'Admin account admin@urbanbites.com logged in from a new device (iPhone 15, Mumbai) at 10:22 AM. Location differs from usual.',
    type: 'warning',
    status: 'read',
    entity: 'Urban Bites',
    entityType: 'user',
    timestamp: '2026-05-16T10:22:00Z',
    tags: ['security'],
  },
  {
    id: '7',
    title: 'Database Backup Completed',
    description: 'Nightly database backup completed successfully. Backup size: 4.2 GB. Stored in primary and secondary regions.',
    type: 'info',
    status: 'resolved',
    entityType: 'system',
    timestamp: '2026-05-16T02:00:00Z',
    resolvedAt: '2026-05-16T02:14:00Z',
    tags: ['system', 'backup'],
  },
];