// src/constants/errors.ts
// Machine-readable error codes — matches PRD Section 18

export const ErrorCode = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  CONFIRM_TEXT_MISMATCH: 'CONFIRM_TEXT_MISMATCH',
  DUPLICATE_ORDER_ATTEMPT: 'DUPLICATE_ORDER_ATTEMPT',

  // Authentication
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  CANNOT_SELF_DEMOTE: 'CANNOT_SELF_DEMOTE',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Session-specific
  SESSION_INVALID: 'SESSION_INVALID',
  SESSION_IDLE_TIMEOUT: 'SESSION_IDLE_TIMEOUT',
  TABLE_SESSION_EXPIRED: 'TABLE_SESSION_EXPIRED',

  // Table-specific
  TABLE_OCCUPIED: 'TABLE_OCCUPIED',
  TABLE_ALREADY_ASSIGNED: 'TABLE_ALREADY_ASSIGNED',
  TABLE_INVALID_TRANSITION: 'TABLE_INVALID_TRANSITION',
  TABLE_INACTIVE: 'TABLE_INACTIVE',
  TABLE_ALREADY_OCCUPIED: 'TABLE_ALREADY_OCCUPIED',
  UNAUTHORIZED_TABLE_SESSION: 'UNAUTHORIZED_TABLE_SESSION',

  // Domain-specific
  ORDER_NOT_MODIFIABLE: 'ORDER_NOT_MODIFIABLE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Phase 2 New Codes
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  TENANT_VIOLATION: 'TENANT_VIOLATION',
  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];
